### ISSUE TITLE
TypeError: Environment must be of type finite_mdp.envs.finite_mdp.FiniteMDPEnv or handle a conversion method called 'to_finite_mdp' to such a type.

### ISSUE THREAD

**Issue by gsanthosh1601** [eleurent/finite-mdp#3]
Hi, Can you help me with this bug?
```

'''
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/RRR/.local/lib/python3.7/site-packages/rl_agents/agents/dynamic_programming/value_iteration.py", line 21, in __init__
    self.mdp = env.unwrapped.to_finite_mdp()
AttributeError: 'FiniteMDPEnv' object has no attribute 'to_finite_mdp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/RRR/PycharmProjects/pythonProject/pacrl/dtp/rswim/gapE/planners_evaluation_confidence.py", line 102, in evaluate
    vi = agent_factory(env, agent_configs()["value_iteration"])
  File "/home/RRR/.local/lib/python3.7/site-packages/rl_agents/agents/common/factory.py", line 24, in agent_factory
    agent = agent_class(environment, config)
  File "/home/RRR/.local/lib/python3.7/site-packages/rl_agents/agents/dynamic_programming/value_iteration.py", line 23, in __init__
    raise TypeError("Environment must be of type finite_mdp.envs.finite_mdp.FiniteMDPEnv or handle a "
TypeError: Environment must be of type finite_mdp.envs.finite_mdp.FiniteMDPEnv or handle a conversion method called 'to_finite_mdp' to such a type.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/RRR/PycharmProjects/pythonProject/pacrl/dtp/rswim/gapE/planners_evaluation_confidence.py", line 238, in <module>
    main(arguments)
  File "/home/RRR/PycharmProjects/pythonProject/pacrl/dtp/rswim/gapE/planners_evaluation_confidence.py", line 227, in main
    list(tqdm.tqdm(p.imap_unordered(evaluate, experiments, chunksize=chunksize), total=len(experiments)))
  File "/home/RRR/gapEnv37/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
TypeError: Environment must be of type finite_mdp.envs.finite_mdp.FiniteMDPEnv or handle a conversion method called 'to_finite_mdp' to such a type.
'''
```

**Comment by gsanthosh1601** [comment]
I am using Python 3.7, gym version 0.26.2.

**Comment by eleurent** [comment]
Hi,
What environment are you running exactly?
It it is a highway-env environment, it should implement the `to_finite_mdp` conversion, see [here](https://github.com/eleurent/highway-env/blob/master/highway_env/envs/common/abstract.py#L386)

**Comment by eleurent** [comment]
Ah sorry, I just realised you are trying to run `planners_evaluation_confidence.py`.
In that case, the default env (garnet) is `finite-mdp-v0` which is indeed defined in this repo, try to install it with:
`pip install --user git+https://github.com/eleurent/finite-mdp`

**Comment by gsanthosh1601** [comment]
`pip install --user git+https://github.com/eleurent/finite-mdp`
I already have done this. Looks like the python file `finite_mdp_env.py` that has the class `FiniteMDPEnv` doesn't implement the `to_finite_mdp` method.

please check the error. error lines 4,5 has the following.
```
self.mdp = env.unwrapped.to_finite_mdp()
AttributeError: 'FiniteMDPEnv' object has no attribute 'to_finite_mdp'
```

**Comment by gsanthosh1601** [comment]
I temporarily fixed it.

the `is_finite_mdp` method in `value_iteration.py`  should `return True`, but it `returns None`.


```
class ValueIterationAgent(AbstractAgent):
    def __init__(self, env, config=None):
        super(ValueIterationAgent, self).__init__(config)
        self.finite_mdp = self.is_finite_mdp(env) #returns None
        self.finite_mdp = True #SantHere Temp fix

        if self.finite_mdp:
            # self.mdp = env.mdp #SantHere Original
            self.mdp = env.unwrapped.mdp

        elif not self.finite_mdp:
            try:
                self.mdp = env.unwrapped.to_finite_mdp()
            except AttributeError:
                raise TypeError("Environment must be of type finite_mdp.envs.finite_mdp.FiniteMDPEnv or handle a "
                                "conversion method called 'to_finite_mdp' to such a type.")
        self.env = env
        self.state_action_value = self.get_state_action_value()


    @staticmethod
    def is_finite_mdp(env):
        try:
            finite_mdp = __import__("finite_mdp.envs.finite_mdp_env") #SantHere Original
            if isinstance(env, finite_mdp.envs.finite_mdp_env.FiniteMDPEnv):
                return True
        except (ModuleNotFoundError, TypeError):
            return False

```

**Comment by eleurent** [comment]
Thanks for figuring this out! There is indeed an error in `is_finite_mdp`, which doesnt handle the fact that the finiteMDP could be wrapped (for instance, since recently the gym is automatically applying wrappers like `gym.wrappers.order_enforcing.OrderEnforcing`). I'll fix it.

**Comment by eleurent** [comment]
It should be fixed now. Thanks again for the feedback
